alerters:
  discord:
    webhook_url: https://discord.com/api/webhooks/927770458949046362/NIRpgnTD0_HoN16YpY-0iP-0D9YMg0yOJVIszXuKdZtIYI8Z4r816a6XgiWlKeyJQ_Mx
    mentions:
      - XXXXXXXXXXXXXXX
      - XXXXXXXXXXXXXXX
  # telegram:
  #   webhook_url: https://api.telegram.org/botXXXXXXXXXXXXXXXXXXXX/sendMessage
  #   chat_id: XXXXXXXX
  # email:
  #   sender: myemail@email.com
  #   recipients:
  #     - myemail@email.com
  #     - myfriendsemail@email.com
  #   relay: 127.0.0.1
  #   password: XXXXXXXXXX # optional
  # slack:
  #   webhook_url: https://hooks.slack.com/services/T00000000/B00000000/XXXXXXXXXXXXXXXXXXXXXXXX
  #   mentions:
  #     - XXXXXXXXXXXXXXX
  #     - XXXXXXXXXXXXXXX
